version: '3.8'
services:
  api_inserts:
    build:
      context: ./inserts
      dockerfile: Dockerfile
    container_name: inserts
    ports:
      - 8000:8000
    env_file:
      - .env.development  
    volumes:
      - ./inserts:/usr/src/app
      - /usr/src/app/node_modules
  my-app:  
    stdin_open: true  
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: my-app  
    ports:
      - 3000:3000
    env_file:
      - .env.development
    volumes:
      - /app/node_modules 
      - ./my-app:/app   
volumes:
  nps_data: {}
